apiVersion: apps/v1
kind: Deployment
metadata:
  name: arsidevops-frontend-deployment
spec:
  selector:
    matchLabels:
      app: arsidevops-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: arsidevops-frontend
    spec:
      containers:
        - name: arsidevops-frontend
          image: arselenebelhayej/arsi-devops-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80  # Typically frontend services run on port 80 for HTTP traffic

---
apiVersion: v1
kind: Service
metadata:
  name: arsidevops-frontend-service
spec:
  selector:
    app: arsidevops-frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: NodePort
